### ISSUE TITLE
access_type missing for OIDC/OAuth. Token expires after one hour.

### ISSUE THREAD

**Issue by dannyyy** [travisghansen/external-auth-server#51] opened 2020-02-02 14:39 UTC
Hi

I'm using the `oidc` auth module to authenticate against Google. My actual problem is, that after an hour I have to re-authenticate against Google. I've read that Google has to be called with the `access_type=offline` to get a `refresh_token`. But I haven't found any possibility to add this to the configuration. I also investigated on the request in the Chrome dev tools and this param is missing.

In addition I don't use Redis. But I only run a single node k3s cluster with just one instance of Traefik v2 and external-auth-server. I guess in this case Redis is optional.

I use the following configuration, just to check whether all the other stuff is correct:
```
let config_token = {
  aud: "mydomain.io",
  eas: {
    plugins: [{
      type: "oidc",
      issuer: {
        discover_url: "https://accounts.google.com/.well-known/openid-configuration",
      },
      client: {
        client_id: "myid.apps.googleusercontent.com",
        client_secret: "mysecret"
      },
      scopes: ["openid", "email", "profile"], // must include openid
    redirect_uri: "https://auth.domain.io/oauth/callback",
    features: {
        cookie_expiry: true,
        userinfo_expiry: true,
        session_expiry: true,
        session_expiry_refresh_window: 60 * 30, // Google's access_token expires within 60min
        session_retain_id: true,
        refresh_access_token: true,
        fetch_userinfo: true,
        introspect_access_token: false, // Not supported by Google
        authorization_token: "access_token"
    },
    assertions: {
        exp: true,
        nbf: true,
        iss: true,
        userinfo: [ {
          query_engine: "jp",
          query: "$.email",
          rule: {
            method: "in",
            value: ["myemailr@gmail.com"],
            case_insensitive: false
          }
        } ]
    },
    cookie: {
        domain: "mydomain.io", 
    },
    headers: {},
}]
  }
};
```

Google's `access_token` has a validity of 60 minutes.

Thank you.
Best Danny

**Comment by travisghansen** [comment] 2020-02-02 15:54
I think this is doable. It's strange they handle it this way as generally I see it managed via an additional scope.

**Comment by dannyyy** [comment] 2020-02-02 16:01
I'm also used to use an additional scope for that. But according to https://developers.google.com/identity/protocols/OpenIDConnect#refresh-tokens there is no additional scope, only the `access_type` parameter.

Maybe it's a good idea to provide a hashmap or something like this to add any extra param to the request. Then stuff like `prompt` can also be controlled.

Thank you very much.

**Comment by travisghansen** [comment] 2020-02-02 16:10
Yeah, I'd make it generic. I need to dig into the client project/library and make sure it supports setting these values. I think I saw it in the past but it's been a while.

**Comment by travisghansen** [comment] 2020-02-03 05:44
I've added a new parameter (`custom_authorization_parameters`) to manage this, try it out and let me know how it goes. It's currently in the `next` image tag until I merge to master and/or tag.

https://github.com/travisghansen/external-auth-server/commit/9eb59c2d48a02b2c8dc8b63fda9aa5057743279a

**Comment by dannyyy** [comment] 2020-02-03 18:11
Thank you, the request to google now inculdes the `access_type=offline` parameter. Is there a simple method to check whether `eas` can retrieve and use it? Because this part is hidden from the browser. According to google, `eas` has to retrieve the `refresh_token` from the token endpoint, together with the other tokens (`id_token` and `access_token`).

I will give you feedback from a front-end perspective whether I have to re-authenticate after an hour or not ;)

**Comment by travisghansen** [comment] 2020-02-03 18:41
OK, yeah `eas` will automatically use the refresh token if it gets sent back by the service. The only way to confirm that google actually sends the refresh token would be to turn on `silly` log level and watch the output. There are various places/lines where you'd see a refresh token if it was present in the session.

**Comment by kettenbach-it** [comment] 2020-02-26 16:56
I turned on the silly loglevel and did not see a refresh token.....
But I don't know how it would look like, either..

**Comment by travisghansen** [comment] 2020-02-26 17:07
@kettenbach-it you should see it when the `tokenSet` gets logged..

https://github.com/travisghansen/external-auth-server/blob/next/src/plugin/oauth/index.js#L516
https://github.com/travisghansen/external-auth-server/blob/next/src/plugin/oauth/index.js#L1015

**Comment by kettenbach-it** [comment] 2020-02-27 13:40
Mmmmh, why does this happen:

`verivinum-external-auth-server    | 2020-02-27T13:38:27.482156670Z verbose: tokenSet is expired and refresh tokens disabled`

here my config:

```
token: {
  "eas": {
    "plugins": [
      {
        "type": "oidc",
        "issuer": {
          "discover_url": "https://accounts.google.com/.well-known/openid-configuration"
        },
        "client": {
          "client_id": "xxx",
          "client_secret": "xxx"
        },
        "scopes": [
          "openid",
          "email",
          "profile"
        ],
        "custom_authorization_parameters": {
          "access_type": "offline"
        },
        "redirect_uri": "https://auth.mydomain.com/oauth/callback",
        "features": {
          "cookie_expiry": false,
          "userinfo_expiry": true,
          "session_expiry": 1209600,
          "session_expiry_refresh_window": 86400,
          "session_retain_id": true,
          "refresh_access_token": true,
          "fetch_userinfo": true,
          "introspect_access_token": false,
          "authorization_token": "access_token"
        },
        "assertions": {
          "exp": true,
          "nbf": true,
          "iss": true
        },
        "cookie": {
          "domain": "mydomain.com",
          "httpOnly": true,
          "secure": true
        },
        "headers": {},
        "custom_service_headers": {
          "X-Forwarded-User": {
            "source": "userinfo",
            "query_engine": "jp",
            "query": "$.email",
            "query_opts": {
              "single_value": true
            }
          }
        }
      }
    ]
  }
}

```

**Comment by travisghansen** [comment] 2020-02-27 15:27
Good question. Are you doing this with a Google account for business or is it some sort of app using normal Gmail accounts? If it's the latter what's the easiest way to create a client id/secret and I'll do some testing locally and see what's going on..

**Comment by kettenbach-it** [comment] 2020-02-27 16:38
It's a GSuite (=business) account. GMail-Users will not have access to this systems

**Comment by travisghansen** [comment] 2020-02-27 16:50
Ok, I'll see what I can come up with to do some testing of my own.

**Comment by kettenbach-it** [comment] 2020-02-27 17:03
If you need an account in GSuite, I can create one for you.

**Comment by travisghansen** [comment] 2020-02-27 17:22
I'll try to setup something on my own to make it more sustainable to test in the future. I'll let you know though if I hit too many road blocks and maybe we'll go that route.

**Comment by travisghansen** [comment] 2020-02-27 18:04
OK, I've got this setup now. I see that I'm actually getting a refresh token back from google but for some reason it's not being stored in the server-side session...I'll do some more digging but should be able to get to the bottom of it pretty easily at this point.

**Comment by kettenbach-it** [comment] 2020-02-27 18:13
I think after waiting another hour, the refresh seems to have worked:

`2020-02-27T18:10:46.982000009Z verbose: re-creating session: 9f44d2b5-e034-4d3c-b73d-2a1079060c0c`

At least it didn't ask to relogin.
But I'm not 100% sure since I'm working on something else in parallel.
I'll see what happens in another hour.

**Comment by travisghansen** [comment] 2020-02-27 18:18
Well, to end-users it may seem like a refresh token was used, but may not have been. If you're already logged into google you just transparently get redirected so you end up with a series of redirects in actuality but the user just ends up seeing on the screen the desired url. You'd have to watch the network in devtools.

Regardless, I think I've discovered at least part of the issue: https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token

I only got the token on the very first auth. It seems there were other scenarios where we refreshed the token and the new tokenSet doesn't actually include the refresh_token...I think a patch was created for that but I'll confirm.

**Comment by travisghansen** [comment] 2020-02-27 18:38
Yeah, I've confirmed the patch is in there and that the `refresh_token` is getting stored properly when present. I've also confirmed that the refresh process works correctly.

In my case (due to `secure` setting on cookie) the first time I tried to load it up I got in an infinite redirect loop. And then due to the missing `prompt=consent` the `refresh_token` was in essence lost in the void. I did as recommended and removed access to the app from my gmail account and re-authenticated and that seems to have worked.

I also have confirmed that the `prompt=consent` does result in a `refresh_token` being returned every auth.

At this point I think code is sound and you'd just need to make a decision based on your needs. You run the risk of the `eas` session being destroyed and therefore losing the `refresh_token` if you don't set `prompt=consent`. If you do set `prompt=consent` then *every* time the session is dead with `eas` the user will be prompted (vs what you likely experienced above where a bunch of redirects happened transparently). Note that the `eas` session's lifetime is (or can be) independent from the lifetime of the `access_token` and more importantly the `refresh_token`. Meaning, if the `eas` session is sufficiently long enough and the refresh window is sufficiently large enough, `eas` will use the `refresh_token` behind the scenes requiring very few new logins from your end users. That's likely the route I would go is to crank up those values fairly high and set `prompt=consent`.

**Comment by kettenbach-it** [comment] 2020-02-27 18:53
I tried to pull the next branch but it seems the patch is not in there:

```
volker@volkers-mbp ~/external-auth-server > git pull
Already up to date.
```

**Comment by kettenbach-it** [comment] 2020-02-27 18:54
By `prompt=consent` you mean a customer-header?

**Comment by travisghansen** [comment] 2020-02-27 18:58
Patch has already been there..referring to this: https://github.com/travisghansen/external-auth-server/blob/next/src/plugin/oauth/index.js#L571

For `prompt=consent` I mean this:

```
          "custom_authorization_parameters": {
            "access_type": "offline",
            "prompt": "consent"
          },
```

**Comment by kettenbach-it** [comment] 2020-02-27 19:04
Ah, okay. I missunderstood your comment on the patch.

I know set `"prompt": "consent"`. We'll see what i does tomorrow. In my timezone it's closing time now.

**Comment by travisghansen** [comment] 2020-02-27 19:05
Yeah, good luck! Let me know how it goes. I would recommend just clearing cookies for good measure and starting fresh when you're ready to test it.

**Comment by kettenbach-it** [comment] 2020-02-28 07:52
My session started yesterday evening at around 10pm was idling through the night until 8:46am.
Reload the static webpage worked without relogin.
The logs show:

```
2020-02-28T07:46:29.754340409Z verbose: refreshing tokenSet
2020-02-28T07:46:29.883662960Z verbose: refreshing userinfo
```

So it seems to work intended!
Cool!
Great work @travisghansen

**Comment by travisghansen** [comment] 2020-02-28 07:57
Perfect!

**Comment by travisghansen** [comment] 2020-02-28 18:05
This has landed in master/latest.

**Closed by travisghansen** 2020-02-28 18:05 UTC
