### ISSUE TITLE
Feature proposal: dynamic server_token_id propagation from request URL

### ISSUE THREAD

**Issue by mlushpenko** [travisghansen/external-auth-server#29] opened 2019-09-02 15:38 UTC
It's been a long time since the last issue =D 

We did another hack to your source code and want to discuss if you think something similar to our hack may be turned into a feature. I will try to explain and would like to hear your thoughts about this. I know it may be too specific to our use-case but let's see.

Last successful setup:
1. Single eas server
2. Many envoy filters where we specify `token_id` per tenant which has to be retrieved from redis. Each filter is applied to istio sidecar, so to specific app, not in general to all publicly exposed services behind ingress.
3. Single `redirect_url` for all tokens

Ignoring the `why`, we thought it would be great to retrieve token dynamically from request subdomain (or URL path for that matter). Then, we can use single filter on ingress level to handle different tokens (token name = tenant name), not on specific sidecar of the service.

So, my colleague added this piece of code to `server.js`:

```
if (easVerifyParams.config_token_regex) {
      let matches = req.get("host").match(new RegExp(easVerifyParams.config_token_regex))
      if (matches && matches[1]) {
        easVerifyParams.config_token_id = matches[1]
      } else {
        externalAuthServer.logger.error("config_token_regex: unexpected number of matches (%j)", matches)
      }
    }
```

and then we changed envoyfilter config to this:
```
headers_to_add:
- key: x-eas-verify-params
   value: '{"config_token_store_id":"primary", "config_token_regex": ".*\\.(.*)\\.k8s.*"}'
```

Basically, we are using regexp to get token name from URL. Then, you can split applications (or tenants, or users) with a single filter if some part or URL matches `config_token_id`.

The last important bit is that we had a single redirect URL for all tokens like `https://istio-eas.hal24k.nl/oauth/callback`

It caused a problem like this:
1. During initial request, `starting verify pipeline` logic was working fine because request host was `https://jupyterhub.tenant-354.k8s.dimension.ws/hub/spawn` and we could capture regexp group.
2. After logging in to OIDC, the host header would be `https://istio-eas.hal24k.nl/oauth/callback` and `starting verify pipeline` would not extract `config_token_id` and the rest would fail.

So, while configuring token, we use specific redirect URL per tenant and point all of them to eas service. The only reason for that is to get tenant name in the host header.

So, current working set up:
1. Modified eas server
2. Single envoy filter on ingress level with `token_id_regexp` 
3. Many `redirect_url` per tenant with include tenant name in the host (but could be url path as well)

Please let us know if you find this interesting and maybe you have better idea how to set this up. So, this could be like another case for config token logic - to use regexp.

**Comment by travisghansen** [comment] 2019-09-03 01:54
I assumed this request would be coming! :) I'll put some thought into it but on the surface I'm more inclined to put together some set of data including everything from the request and allowing querying the dataset via jp or jq to produce a result for both store and token.

The callback url endpoint shouldn't be an issue but let me think about it a little. I can't think why it would pose a problem unless auth is occurring for eas itself. All that endpoint does is redirect back to the original URL so the token isn't even used.

**Comment by mlushpenko** [comment] 2019-09-03 08:17
`I can't think why it would pose a problem unless auth is occurring for eas itself.` I will double-check, good point - we changed where the filter is applied so that must be the reason.

As for jp/jq, I think it wouldn't suffice for this use case as we are trying to extract data from a subdomain (or url path), not just compare, but that could be our specific use-case.

Thanks for the quick response :)

**Comment by mlushpenko** [comment] 2019-09-03 10:10
We got it working after excluding eas from auth by using another gateway port and service for eas. So, eas is exposed via `https://auth.k8s.dimension.ws:445` and everything else that comes on port 443 is protected by single eas instance, with single envoyfilter and single redirect URL - awesome! :) 

We'll stick with a piece of code I provided above for now until you implement something better. Maybe if you provide subdomains in a list like [here](http://expressjs.com/uk/api.html#req.subdomains) then jp/jq could work, but I still think regexp groups are more flexible.

**Comment by travisghansen** [comment] 2019-09-03 13:32
That whole `req` object would be part of the datset yes (but it would be the eas data). I'd also throw the `parentRequestInfo` in there as well... basically as much as we could. 

`jq` supports regex stuff...it's extremely powerful so you should be able to build whatever you can dream up with that for sure.

**Comment by mlushpenko** [comment] 2019-09-03 13:50
Ah, I missed that, awesome then, looking forward

**Comment by travisghansen** [comment] 2019-09-06 14:00
Forgot to mention it would be a little bit until I can get to this FYI. Probably another week or two..

**Comment by mlushpenko** [comment] 2019-09-07 13:20
Thanks anyway, we have a working version for now and will migrate to your latest release whenever it is ready and we tested it.

**Comment by travisghansen** [comment] 2019-10-09 17:54
Will be looking into this over the next couple days as an FYI.

**Comment by mlushpenko** [comment] 2019-10-09 22:51
Thanks, Travis, I was busy with two blog posts https://medium.com/hal24k-techblog/multitenancy-on-kubernetes-with-istio-external-authentication-server-and-openid-connect-33e02544e0db and some releases. We are starting to use jwt plugin as well for API backends - you were asking some time ago to share our usage of your project, I think it will increase over time and become a central piece of our infrastructure.

**Comment by travisghansen** [comment] 2019-10-09 23:53
Wow awesome! Excited to read over the blog post!

**Comment by travisghansen** [comment] 2019-10-12 21:07
Can you share an example of the id you are generating with your regex? I want to make sure I can reproduce with `jq` etc

**Comment by travisghansen** [comment] 2019-10-12 21:08
BTW, loved the article, it was a great read! If you weren't already aware `eas` can parse tokens and pass those values down as arbitrary header values etc.

**Comment by travisghansen** [comment] 2019-10-12 22:08
I've committed to the `next` (images are built and ready to test) branch the introduction of 4 new params:
1. `config_token_id_query_engine`
1. `config_token_id_query`
1. `config_token_store_id_query_engine`
1. `config_token_store_id_query`

`engine` values should be `jp` or `jq` and query should be formatted appropriately for the supplied `engine`.

Each pair must be used simultaneously. Meaning, you must set both the `query_engine` and `query` parameter for the applicable `id`. However, both `id`s are independent so you could still statically set the `config_token_store_id` and set the `config_token_id_query_engine` **AND** `config_token_id_query` params.

I don't claim to be an expert with `jq`, but I find it highly unlikely you won't be able to query/construct the data you need with it. Here's an example I was testing with:

```
# jq
# .parentRequestInfo.parsedUri.host | split(".")[0]
# get the leading segment/portion of the request host (ie: foo.bar.baz.com would return foo as the config_token_id)
http://127.0.0.1:9000/verify?fallback_plugin=5&config_token_store_id=dep_a&config_token_id_query_engine=jq&config_token_id_query=.parentRequestInfo.parsedUri.host+%7C+split%28%22.%22%29%5B0%5D
```

Give a try and let me know how it goes. Once we confirm it's working as desired I'll pull into master and tag a new release.

Thanks!

**Comment by travisghansen** [comment] 2019-10-12 22:16
Reading through the logs you emailed on the other issue I see the query you probably want to use is this: `.parentRequestInfo.parsedUri.host | split(".")[1]`

**Comment by mlushpenko** [comment] 2019-10-14 09:41
> BTW, loved the article, it was a great read! If you weren't already aware `eas` can parse tokens and pass those values down as arbitrary header values etc.

Thanks, both for the article and your suggestion. Passing headers with user info was the first thing that came to my mind, even without EAS, but all our backends still have direct integration with our identity server. 

Basically, we had a discussion on security and decided on a middle ground: EAS integrates with the identity server and also passes tokens to backends for final validation. A bit of a double-work, but turned out that's what Google [recommends](https://developers.google.com/identity/sign-in/web/backend-auth) as well, main security concern being `A modified client application can send arbitrary user IDs to your server to impersonate users, so you must instead use verifiable ID tokens to securely get the user IDs of signed-in users on the server side.`

We are going to test your new code today and report back soon, thanks!

**Comment by travisghansen** [comment] 2019-10-14 13:46
Yeah that's something to be careful with for sure.

**Comment by mlushpenko** [comment] 2019-10-14 15:11
Hey, @travisghansen, thanks again for the new code, everything seems great so far and don't see problem with URL anymore, so I guess two issues are killed on a new branch :) 

This is our filter right now:

```
filters:
  - filterConfig:
      httpService:
        authorizationRequest:
          allowedHeaders:
            patterns:
            - exact: cookie
            - exact: X-Forwarded-Host
            - exact: X-Forwarded-Method
            - exact: X-Forwarded-Proto
            - exact: X-Forwarded-Uri
          headers_to_add:
          - key: x-eas-verify-params
            value: '{"config_token_store_id":"primary","config_token_id_query_engine":"jq","config_token_id_query":".parentRequestInfo.parsedUri.host|split(\".\")[1]"}'
        authorizationResponse:
          allowedUpstreamHeaders:
            patterns:
            - exact: Authorization
            - exact: X-Id-Token
        pathPrefix: /envoy/verify-params-header
        serverUri:
          cluster: outbound|8080||eas.auth.svc.cluster.local
          failureModeAllow: false
          timeout: 10s
          uri: http://eas.auth.svc.cluster.local:8080
      statusOnError:
        code: Unauthorized
    filterName: envoy.ext_authz
    filterType: HTTP
    insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: GATEWAY
      portNumber: 443
  workloadLabels:
    istio: multitenant-ingress
```

and following logs for two different services:

```
{"service":"external-auth-server","level":"silly","message":"verify request details: {\"url\":\"/envoy/verify-params-header/\",\"params\":{\"0\":\"/\",\"1\":\"\"},\"query\":{},\"http_method\":\"GET\",\"http_version\":\"1.1\",\"headers\":{\"host\":\"vpm.amir-tenant-354.cloud.dimension.ws\",\"content-length\":\"0\",\"x-forwarded-proto\":\"https\",\"cookie\":\"_ga=GA1.2.362787940.1568711422; _eas_oauth_session=s%3Ae8f538fd-cf88-4864-a94e-d4c566f6b155.RsqIxYe72844l%2BvepvkwsvNdGueA0dg227aJ9USI574\",\"x-eas-verify-params\":\"{\\\"config_token_store_id\\\":\\\"primary\\\",\\\"config_token_id_query_engine\\\":\\\"jq\\\",\\\"config_token_id_query\\\":\\\".parentRequestInfo.parsedUri.host|split(\\\\\\\".\\\\\\\")[1]\\\"}\",\"x-forwarded-for\":\"10.255.203.186\",\"x-envoy-expected-rq-timeout-ms\":\"10000\",\"x-envoy-internal\":\"true\",\"x-request-id\":\"f6d96c5f-c04b-4d95-9dc7-31bd6bc9a496\",\"x-forwarded-client-cert\":\"By=spiffe://cluster.local/ns/auth/sa/default;Hash=f64f2178de541af2394c410fa5b4c300bef0c166a63828dc6f3c1632862ca69a;Subject=\\\"\\\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingress-multitenant-service-account\",\"x-b3-traceid\":\"af91e918cd717a8a95d10f8133d0c7c4\",\"x-b3-spanid\":\"95d10f8133d0c7c4\",\"x-b3-sampled\":\"0\",\"x-forwarded-uri\":\"/\"},\"body\":{}}"}

{"service":"external-auth-server","level":"silly","message":"verify request details: {\"url\":\"/envoy/verify-params-header/hub/home\",\"params\":{\"0\":\"/hub/home\",\"1\":\"hub/home\"},\"query\":{},\"http_method\":\"GET\",\"http_version\":\"1.1\",\"headers\":{\"host\":\"datalab.amir-tenant-354.cloud.dimension.ws\",\"content-length\":\"0\",\"x-forwarded-proto\":\"https\",\"cookie\":\"jupyterhub-hub-login=\\\"2|1:0|10:1571058498|20:jupyterhub-hub-login|44:ZmY1MmM2NDNlZWE0NGE3OGIwNzJjNGRmN2M0YTgzZmY=|6c907d9f0c8fe8f716fed81b108f702c3b6d9b2c1129123757fe2bc6227e1fa3\\\"; _ga=GA1.2.362787940.1568711422; _eas_oauth_session=s%3Ae8f538fd-cf88-4864-a94e-d4c566f6b155.RsqIxYe72844l%2BvepvkwsvNdGueA0dg227aJ9USI574; jupyterhub-session-id=d1521e6b307f4e3dbd43ff6bc9d6d1e0; _eas_oauth_csrf=s%3A0fpIDV8UKxy5qHiCP0hPI88YzVvXHM090EQt5RRr3ulQ%2BptBGwwHDg73kcuoYede.I9WkRxeh0Q2PTJIRLynkm9pN%2BI%2Fu5kiBsUBWvUOFGFg\",\"x-eas-verify-params\":\"{\\\"config_token_store_id\\\":\\\"primary\\\",\\\"config_token_id_query_engine\\\":\\\"jq\\\",\\\"config_token_id_query\\\":\\\".parentRequestInfo.parsedUri.host|split(\\\\\\\".\\\\\\\")[1]\\\"}\",\"x-forwarded-for\":\"10.255.203.186\",\"x-envoy-expected-rq-timeout-ms\":\"10000\",\"x-envoy-internal\":\"true\",\"x-request-id\":\"15f1a335-f14a-4ef6-9b50-bae5b67d0190\",\"x-forwarded-client-cert\":\"By=spiffe://cluster.local/ns/auth/sa/default;Hash=f64f2178de541af2394c410fa5b4c300bef0c166a63828dc6f3c1632862ca69a;Subject=\\\"\\\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingress-multitenant-service-account\",\"x-b3-traceid\":\"d7210dfc57f6d070f68d0c2de3393c25\",\"x-b3-spanid\":\"f68d0c2de3393c25\",\"x-b3-sampled\":\"0\",\"x-forwarded-uri\":\"/hub/home\"},\"body\":{}}"}
```

**Comment by travisghansen** [comment] 2019-10-14 22:06
Ok, alternatively, you could remove the `X-Forwarded-Uri` from the allowed headers and all should work fine with current `latest`.

I'll leave this ticket open until it merges to master and a new release is snapped. This is a really powerful feature so thanks for the suggestion!

**Comment by travisghansen** [comment] 2019-10-21 13:39
I did some performance testing with jq and it's magnitudes slower than jp unfortunately. For simple cases where jp is viable I recommend using it. So for your dynamic token detection I'd for sure recommend using the jp equivalent FYI.

**Comment by mlushpenko** [comment] 2019-10-21 14:06
Thanks @travisghansen, we'll try that. I did notice some lag when we try opening a new page, but also I think there are many more logs in EAS now, seems like more requests are being made for every webpage or maybe it's just my impression and I need to disable silly log level.

**Comment by travisghansen** [comment] 2019-10-21 14:24
Some details here: https://github.com/sanack/node-jq/issues/222

**Comment by mlushpenko** [comment] 2019-10-23 22:40
I just came back from bar, so perhaps not the best judgement :) but on the
page you shared it states jq.node is less performant than jq itself.

I trust your judgement - I think if several good examples are added to the
docs, it could work, otherwise: jq or jsonpath are more widespread than
knowledge of JavaScript (my assumption, I may be wrong here)

Also wondering if JavaScript snippets can be easily used in headers like jq
or jp right now, meaning if it won't get ugly.

**Comment by travisghansen** [comment] 2019-10-23 23:46
Ha! Yeah for our use case it seems much faster than jq based on crude tests. I really like `jq` but the performance issue could be problematic in aggregate. `jp` is fine for simplistic stuff but it doesn't let you arbitrarily add text or select on multiple fields and things like that.

For example, in the jqn pipeline I've got the following:

```
let foo = await jqn_query("thru( function(el) { return { foo: el.kind, bar: el.items[0].etag, baz: 'baz'}; } )", data);
```
Which takes the full data, let's me arbitrarily morph it to whatever I want, and then 'pipe' it to the next operation (no piping in the example however). So it would be pretty easy to create a string based on request data that's something like `<VERB>-<host>-<path>` and then compare the value against a hard-coded value in the config assertion.

Anyway, mostly just thinking out loud at this point...I also don't like that it's 'non-standard' stuff, but it could be extremely powerful and performant.

**Comment by mlushpenko** [comment] 2019-10-24 11:45
`<VERB>-<host>-<path> and then compare the value against a hard-coded value in the config assertion.` this sounds good to me, I thought you had an idea of putting javascript snippets in the header :) Whenever you have that ready, I am happy to test.

One more idea is maybe to use the pattern you described for most configurations and allow some folks to write custom javascript loaded via configmap if they want something more advanced. But combinations of verb, host and path (and maybe port) should already allow for most scenarios.

**Comment by travisghansen** [comment] 2019-10-24 14:11
Well, this effectively let's you write custom assertions using a subset of JavaScript and you would simply put the query in the `config_token` like we do all the other queries. In the end however, operators would be able to do pretty much anything they could dream up (mostly focused on the idea of a plugin to allow endpoints to bypass 'auth' currently). I'll probably mock it up in a branch I guess and go from there.

**Comment by travisghansen** [comment] 2019-10-25 18:08
Just spent a few minutes prototyping this...it's insanely powerful.  Here's a simple example to illustrate the idea:

```
"aud": "development",
    "eas": {
      "plugins": [
        {
          "type": "request_js",
          "snippet": "console.log(data);console.log(process.env); if (data.req.method == 'GET') data.res.statusCode = 200;",
          "assertions": {}
        }
      ]
    }
```

Basically allows for writing custom plugins via `config_token`! That snippet has direct access to the internal `req` and `res` object with the ability to modify headers (req or res), set cookies, status code, etc. There's obviously security considerations of this as it allows token creators the potential to access to container/pod/network/etc so I'll for sure need to make a flag to enable/disable the use of this plugin. If the environment is trusted however, it's super powerful.

**Comment by travisghansen** [comment] 2019-10-25 21:54
I've pushed this to `next` branch. You must set the environment variable `EAS_ALLOW_EVAL` for it to execute the plugin.

Here's a sample:

```
    "aud": "development",
    "eas": {
      "plugins": [
        {
          "type": "request_js",
          "snippet": "console.log(parentReqInfo); if (req.method == 'GET') res.statusCode = 200; res.setHeader('foo', 'bar'); console.log(res);",
          "assertions": {}
        }
      ]
    }
```

You should be able to allow any given path(s) public access pretty easily with that. If you put it at the end of your plugin list all normal auth will still run and pass down headers/etc if that's of benefit. If you put it at the front of the plugin list auth will succeed immediately so no userinfo/tokens/etc would make it to the backing service.

**Comment by travisghansen** [comment] 2019-10-25 21:56
I added support in the helm chart to set arbitrary `env` vars too. `--set env.EAS_ALLOW_EVAL.value=1`

**Comment by mlushpenko** [comment] 2019-10-28 10:58
@travisghansen if I understood correctly, we would use the snippet you showed as the first plugin in the plugin list for the public endpoints with the logic like:

`if request.host = "public_api.example.com" then ALLOW`

And then, if the request isn't allowed there, the next plugin with OIDC will be invoked.

But do you have an idea of how this should work together with `config_token` as we have it right now? Something like this?

```
- key: x-eas-verify-params
   value: '{"config_token_store_id":"primary","config_token_id_query_engine":"request_js","snippet":"req.parsedUri.host|split(\".\")[1]"}'
```

**Comment by travisghansen** [comment] 2019-10-28 14:22
Sorry, we're crossing wires currently. I may add it as a query engine option as well but not there yet. As of now it's simply a brand new plugin so it would be stored as part of your server side `config_token` like any other `plugin`.

I probably will add it as a possible `query_engine` as well. Also looking at `jsonata` project as another potential `query_engine` (https://github.com/jsonata-js/jsonata/issues/384).

**Comment by mlushpenko** [comment] 2019-10-28 15:35
Looks powerful as well. I will try to test plugin for public setup and let you know. Thanks!

**Comment by travisghansen** [comment] 2019-10-28 16:01
Yeah, in the mean time, I'll implement both as `query_engine`s and commit. The raw js query engine will just be `js` (as opposed the plugin `request_js`).

As I get ready to head into a `1.0` release much of the code/configuration will be made more generic than it is today. I think enough features have been added at this point to start seeing some common patterns that make will make the structure of the project more clean. Pretty excited about the new options these ideas introduce!

**Comment by travisghansen** [comment] 2019-10-28 18:27
OK, committed 2 new `query_engine` options, `js` and `jsonata`. Note that the `js` engine is literally executing whatever code you put into the 'query' section. As such, the reference to all the data is available as the variable `data`. So to access `parentRequestInfo` for this particular issue's use-case it would be `data.parentRequestInfo` (ie: `console.log(data.parentRequestInfo)` would dump the whole value to console). Give it a go and let me know what you think.

**Comment by travisghansen** [comment] 2019-10-29 03:27
Here's another example (for assertions), all 3 yield the same results:

```
{
  "query_engine": "jp",
  "query": "$.login",
  "rule": {
    "method": "eq",
    "value": "travisghansen"
  }
}

{
  "query_engine": "jsonata",
  "query": "login",
  "rule": {
    "method": "eq",
    "value": "travisghansen"
  }
}

{
  "query_engine": "js",
  "query": "return data.login;",
  "rule": {
    "method": "eq",
    "value": "travisghansen"
  }
}
```

**Comment by travisghansen** [comment] 2019-10-29 22:13
Released in `v0.6.0`. Leaving open for a little feedback.

**Comment by mlushpenko** [comment] 2019-10-29 22:32
Thanks, @travisghansen. Sorry for the delay on my side, got our dev cluster down today, partially due to cilium network issues https://github.com/cilium/cilium/pull/9519 and partially due to AKS network issues https://github.com/Azure/AKS/issues/1121, keeps me busy :) Hope I can test your updates tomorrow.

**Comment by travisghansen** [comment] 2019-10-29 22:43
Yeah no worries! I documented the new stuff decently so if you need some help figuring something out let me know.

**Comment by mlushpenko** [comment] 2019-11-04 19:11
Hey, @travisghansen, finally got some time to get back to this. Just tested dynamic id via jsonata (couldn't find `split` function in jsonpath and also didn't remember if you added jsonata as a plugin for config tokens and luckily you did)

```
- key: x-eas-verify-params
  value: '{"config_token_store_id":"primary","config_token_id_query_engine":"jsonata","config_token_id_query":"$split(parentRequestInfo.parsedUri.host, \".\")[1]"}'
```

Works well and feels quite fast, unless it's just a happy perception :) I will try to test public URLs tomorrow and get back to you. Thanks again!

**Comment by travisghansen** [comment] 2019-11-04 20:57
Nice! Thanks for the update!

**Comment by mlushpenko** [comment] 2019-11-07 22:39
Testing postponed a bit, I tried quick test with this:
```
      {
        type: "request_js",
        "snippet": "if (parentReqInfo.parsedUri.host.includes('auth')) res.statusCode = 200;",
        pcb: {
          stop: [
            {
              query_engine: "jp",
              query: "$.req.headers.host",
              rule: {
                method: "regex",
                value: "/^auth/i",
              }
            }
          ]
        }
      },
```

plus jwt and openid plugins after `request_js` one, but didn't work well. Due to filter for getting `token_id` from the URL, it tried to get token from `auth.dimension.ws`, while I was expecting that plugin will stop on `request_js` and won't try getting a token for OIDC. Need some more testing, maybe `$.req.headers.host` doesn't return actual host even though I did some tests before and it seemed ok, or I need to change regex to `/^auth.*/i` instead of `/^auth/i`

**Comment by travisghansen** [comment] 2019-11-08 03:29
Maybe give some examples of what you are protecting vs not and I can help draft up a snippet.

**Comment by mlushpenko** [comment] 2019-11-08 13:32
`https://auth.haldev-cloud.dimension.ws` should be open as we discussed that eas shouldn't authentication itself. 

And others like `https://datalab.amir-tenant-354.haldev-cloud.dimension.ws/` should be protected, where `amir-tenant-354` is extracted token name.

The error I got was that eas tried to get `haldev-cloud` token from `https://auth.haldev-cloud.dimension.ws` due to this part: `"config_token_id_query":"$split(parentRequestInfo.parsedUri.host, \".\")[1]"` While I was expecting it to stop with plugin evaluation due to 200 response and PCB rule. I will do some more testing soon.

**Comment by travisghansen** [comment] 2019-11-08 13:51
Ok, I wouldn't use this feature for the use case of ensuring eas itself is not self-authenticating..is that the only use case? Do you have others?

**Comment by mlushpenko** [comment] 2019-11-08 14:22
Ouch :) That was one important use-case as several people had troubles authenticating to our platform if we expose EAS on a different port than 443 because some IT admins block all other ports. But we could create another load balancer just for `auth`, although feels a bit like a waste.

Another use-case is if an application has some public API, like `example.com/public` while all other paths are protected, then it should work with one of the examples you posted in docs.

**Comment by mlushpenko** [comment] 2019-11-08 14:29
Another option for us is to upgrade to Istio 1.3 where we can use full syntax of Envoy filters and use [per-route authorization](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#config-filter-http-ext-authz-v2-extauthzperroute). At least that's the idea, not sure it works yet. Istio guys tend to change spec quite a bit, so it may involve some work to migrate, although they did warn EnvoyFilter config may change drastically.

**Comment by mlushpenko** [comment] 2019-11-08 14:32
No worries if it doesn't work, we have some backup options and the whole setup already works in general, so we are focusing on some optimizations right now. You helped a lot already :)

**Comment by travisghansen** [comment] 2019-11-08 14:34
Yeah that sounds much better. The reason I advise against the first use case is that would require every single config token ever issued to have the rule embedded...seems like the 'wrong' place to handle the issue. Your last comment seems like the 'right' place to handle the issue. It will work, just seems like a maintenance nightmare.

The feature is directly geared at the second use case you mentioned.

In either case, if you need some input getting it going let me know!

**Comment by travisghansen** [comment] 2019-11-14 16:01
Got what you need on this one?

**Comment by mlushpenko** [comment] 2019-11-14 16:13
I guess so, we tested yesterday `request_js` to return 200 for preflight CORS requests and it worked like a charm, but at the same time migrated to Istio 1.3 and moved it there not to include it in every token.

It turned out Istio doesn't yet support `per_route_authz`, so we still have a problem I described before, but this issue can be closed, dynamic tokens working great, thanks again :)

**Comment by travisghansen** [comment] 2019-11-14 16:52
Oh wow that's a great use case for `request_js`! I had not thought of that.

**Closed by travisghansen** 2019-11-14 16:52 UTC
